#!/bin/bash

set -e -x

cd smbdriver/

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH

go install github.com/onsi/ginkgo/ginkgo@latest

ginkgo -mod vendor -r -keepGoing -p -trace -randomizeAllSpecs -progress --race
