#!/bin/bash

set -e -x

cd smbdriver/

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH

go get github.com/onsi/ginkgo/ginkgo

ginkgo -mod vendor -r -keepGoing -p -trace -randomizeAllSpecs -progress --race
