name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - uses: actions/checkout@v3
      - run: go run github.com/onsi/ginkgo/v2/ginkgo -r
